refactor(ghostty): make ghostty optional but not default

diff --git a/default/bash/aliases b/default/bash/aliases
--- a/default/bash/aliases
+++ b/default/bash/aliases
@@ -16,7 +16,7 @@ if command -v zoxide &> /dev/null; then
     elif [ -d "$1" ]; then
       builtin cd "$1"
     else
-      z "$@" && printf "\U000F17A9 " && pwd || echo "Error: Directory not found"
+      z "$@" && printf "󱞩 " && pwd || echo "Error: Directory not found"
     fi
   }
 fi
